//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GuessNumber.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GuessNumber.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect number of attempts.
        /// </summary>
        public static string AttemptException {
            get {
                return ResourceManager.GetString("AttemptException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application generates an integer number from 0 till 100 (included).
        ///User entes a number, trying to guess the computer&apos;s number. Copyright 2023.
        /// </summary>
        public static string Greeting {
            get {
                return ResourceManager.GetString("Greeting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My number is smaller..
        /// </summary>
        public static string MessageBigger {
            get {
                return ResourceManager.GetString("MessageBigger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Congratulation, you guess!.
        /// </summary>
        public static string MessageCongrat {
            get {
                return ResourceManager.GetString("MessageCongrat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong data..
        /// </summary>
        public static string MessageError {
            get {
                return ResourceManager.GetString("MessageError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game is finish..
        /// </summary>
        public static string MessageFinish {
            get {
                return ResourceManager.GetString("MessageFinish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You lose. .
        /// </summary>
        public static string MessageLose {
            get {
                return ResourceManager.GetString("MessageLose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My number is bigger..
        /// </summary>
        public static string MessageSmaller {
            get {
                return ResourceManager.GetString("MessageSmaller", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Try guess my number.
        /// </summary>
        public static string MessageStart {
            get {
                return ResourceManager.GetString("MessageStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press &apos;Y&apos; to play again..
        /// </summary>
        public static string MessageTryAgain {
            get {
                return ResourceManager.GetString("MessageTryAgain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a number, attempts left: {0}.
        /// </summary>
        public static string MessageTryToGuess {
            get {
                return ResourceManager.GetString("MessageTryToGuess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value of min is greater than max.
        /// </summary>
        public static string RangeException {
            get {
                return ResourceManager.GetString("RangeException", resourceCulture);
            }
        }
    }
}
